FROM node:12.2.0

ENV appDir=/app

WORKDIR ${appDir} 

COPY ./package.json .

RUN npm install

COPY . .

RUN npm install -g @angular/cli

# install chrome for protractor tests
RUN wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
RUN sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
RUN apt-get update && apt-get install -yq google-chrome-stable

EXPOSE 4200 49153

CMD ["npm", "start"]


