language: node_js
node_js: 12.2.0

sudo: required

services:
  - docker

before_install:
  - docker build -t johnmutuma5/phone-num-gen -f ./docker/dev/Dockerfile . 

script:
  - docker run johnmutuma5/phone-num-gen npm run test -- --watch=false --codeCoverage=true
