language: node_js
node_js: 12.2.0

sudo: required

services:
  - docker

script:
  - docker-compose up -d client
  - docker-compose exec client npm run test -- --watch=false --codeCoverage=true

after_success:
  - docker-compose exec client bash -c "cat /app/coverage/phone-num-gen/lcov.info  | /app/node_modules/coveralls/bin/coveralls.js"
  - docker-compose down
