version: "3"
services:
  client:
    build:
      context: .
      dockerfile: ./docker/dev/Dockerfile
    ports:
      - "4200:4200"
      - "49153:49153"
      - "9876:9876"
    volumes:
      - /app/node_modules
      - .:/app



